name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '17 3 * * 1'

permissions:
  contents: write
  actions: write

jobs:  
  check:
    name: Pre-check
    runs-on: 'ubuntu-latest'
    steps:
    - run: gh run list --limit 1 --workflow nightly.yml --json headSha --template "{{range .}}SHA={{.headSha}}{{end}}" --status completed --repo ${{ github.repository }} >> "$GITHUB_OUTPUT"
      id: last_run
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Print
      run: |
        echo Last sha: ${{ steps.last_run.outputs.sha }}
        echo Current:  ${{ github.sha }}
        echo Should cancel: ${{ steps.last_run.outputs.sha == github.sha }}
        echo ${{ github.workflow_ref }}
        echo ${{ github.action_path }}

    - if: ${{ steps.last_run.outputs.sha == github.sha }}
      run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
      env:
        GH_TOKEN: ${{ github.token }}

  build:
    name: Build
    needs: [check]
    uses: ./.github/workflows/reusable-build.yml
    
  virustotal:
    needs: [build]
    name: VirusTotal Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - name: Download Windows x64
        uses: actions/download-artifact@v5
        with:
          name: extension-x64-windows
          path: .
  
      - name: Download Linux x64
        uses: actions/download-artifact@v5
        with:
          name: extension-x64-linux
          path: .
          
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_APIKEY }}
          request_rate: 4
          files: |
            ./dynops_x64.dll
            ./dynops_x64.so

  pre-release:
    needs: [build]
    name: Publish pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Addon
      uses: actions/download-artifact@v5
      with:
        name: addon
        path: .
        
    - name: Push pre-release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development build"
        files: dynops-latest.zip
